language: node_js
node_js:
  - 8
before_script:
  - npm install @11ty/eleventy -g
script: npm run lint && eleventy --pathprefix="/sindre-is/"
deploy:
  local-dir: public
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
