name: Audit pull request
on: push

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Lighthouse Audit
        uses: jakejarvis/lighthouse-action@v0.3.2
        with: https://sindre.is
