name: Node CI

on: [push]

jobs:
  validate-types:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3

      - name: Install npm dependencies
        uses: bahmutov/npm-install@v1

      - name: Validate types
        run: npm run validate-types

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3

      - name: Install npm dependencies
        uses: bahmutov/npm-install@v1

      - name: Lint
        run: npm run lint

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3

      - name: Install npm dependencies
        uses: bahmutov/npm-install@v1

      - name: Test
        run: npm test
        env:
          CI: true

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3

      - name: Install npm dependencies
        uses: bahmutov/npm-install@v1

      - name: Build
        run: npm run build
